#!/usr/bin/env python3
"""
Demo: IDE Integration Features
Demonstrates VS Code and JetBrains IDE integration with inline diffs, quick actions, and code lenses
"""

import asyncio
from pathlib import Path
from src.codegenie.integrations.ide_bridge import (
    VSCodeBridge,
    JetBrainsBridge,
    IDEEvent,
    IDEEventType
)
from src.codegenie.integrations.ide_features import QuickActionType


async def demo_vscode_integration():
    """Demonstrate VS Code integration"""
    print("=" * 60)
    print("VS Code Integration Demo")
    print("=" * 60)
    
    # Initialize VS Code bridge
    project_root = Path.cwd()
    vscode = VSCodeBridge(project_root)
    
    # Initialize extension
    init_result = await vscode.initialize()
    print("\n1. Extension Initialized:")
    print(f"   Capabilities: {list(init_result['capabilities'].keys())}")
    print(f"   Server: {init_result['serverInfo']['name']}")
    
    # Simulate file opened event
    test_file = project_root / "test_example.py"
    event = IDEEvent(
        event_type=IDEEventType.FILE_OPENED,
        file_path=test_file,
        line=0,
        column=0
    )
    await vscode.handle_event(event)
    print(f"\n2. File Opened: {test_file.name}")
    
    # Show inline diff
    print("\n3. Inline Diff Preview:")
    await vscode.show_inline_diff(
        file_path=test_file,
        start_line=5,
        start_column=0,
        end_line=5,
        end_column=20,
        original_text="def old_function():",
        modified_text="def new_function():",
        description="Rename function"
    )
    print("   ✓ Inline diff created for function rename")
    
    # Register quick actions
    print("\n4. Quick Actions:")
    
    # Fix error action
    await vscode.register_quick_action(
        action_id="fix_import_error",
        title="Add missing import",
        action_type=QuickActionType.ADD_IMPORT,
        file_path=test_file,
        start_line=10,
        start_column=0,
        end_line=10,
        end_column=10,
        command="codegenie.addImport",
        arguments=[str(test_file), "from typing import List"]
    )
    print("   ✓ Quick action: Add missing import")
    
    # Refactor action
    await vscode.register_quick_action(
        action_id="extract_method",
        title="Extract method",
        action_type=QuickActionType.REFACTOR,
        file_path=test_file,
        start_line=15,
        start_column=4,
        end_line=20,
        end_column=0,
        command="codegenie.refactor",
        arguments=[str(test_file), "extract_method", 15, 20]
    )
    print("   ✓ Quick action: Extract method")
    
    # Add code lenses
    print("\n5. Code Lenses:")
    
    # Run test lens
    await vscode.add_code_lens(
        file_path=test_file,
        line=25,
        column=0,
        command="codegenie.runTest",
        title="▶ Run test_example",
        arguments=[str(test_file), "test_example"]
    )
    print("   ✓ Code lens: Run test")
    
    # References lens
    await vscode.add_code_lens(
        file_path=test_file,
        line=30,
        column=0,
        command="codegenie.showReferences",
        title="5 references",
        arguments=[str(test_file), 30, "MyClass"]
    )
    print("   ✓ Code lens: Show references")
    
    # Show webview
    print("\n6. Webview Panel:")
    html_content = """
    <html>
        <body>
            <h1>CodeGenie Analysis</h1>
            <p>Code quality: Excellent</p>
            <p>Test coverage: 85%</p>
        </body>
    </html>
    """
    await vscode.show_webview(
        title="CodeGenie Analysis",
        html=html_content,
        view_column=2
    )
    print("   ✓ Webview panel created")
    
    # Create terminal
    print("\n7. Integrated Terminal:")
    terminal_id = await vscode.create_terminal("CodeGenie", project_root)
    print(f"   ✓ Terminal created: {terminal_id}")
    
    await vscode.send_terminal_text(terminal_id, "echo 'Hello from CodeGenie'\n")
    print("   ✓ Command sent to terminal")
    
    # Apply workspace edit
    print("\n8. Workspace Edit:")
    edits = {
        str(test_file): [
            {
                'range': {
                    'start': {'line': 0, 'character': 0},
                    'end': {'line': 0, 'character': 0}
                },
                'newText': '# Generated by CodeGenie\n'
            }
        ]
    }
    await vscode.apply_workspace_edit(edits)
    print("   ✓ Workspace edit applied")
    
    print("\n✅ VS Code integration demo complete!")


async def demo_jetbrains_integration():
    """Demonstrate JetBrains IDE integration"""
    print("\n" + "=" * 60)
    print("JetBrains IDE Integration Demo")
    print("=" * 60)
    
    # Initialize JetBrains bridge
    project_root = Path.cwd()
    jetbrains = JetBrainsBridge(project_root, ide_type="PyCharm")
    
    # Initialize plugin
    init_result = await jetbrains.initialize()
    print("\n1. Plugin Initialized:")
    print(f"   IDE: {init_result['pluginInfo']['ide']}")
    print(f"   Plugin: {init_result['pluginInfo']['name']}")
    print(f"   Capabilities: {list(init_result['capabilities'].keys())}")
    
    # Simulate file opened
    test_file = project_root / "test_example.py"
    event = IDEEvent(
        event_type=IDEEventType.FILE_OPENED,
        file_path=test_file
    )
    await jetbrains.handle_event(event)
    print(f"\n2. File Opened: {test_file.name}")
    
    # Show inline diff
    print("\n3. Inline Diff Preview:")
    await jetbrains.show_inline_diff(
        file_path=test_file,
        start_line=8,
        start_column=0,
        end_line=8,
        end_column=15,
        original_text="class OldClass:",
        modified_text="class NewClass:",
        description="Rename class"
    )
    print("   ✓ Inline diff created for class rename")
    
    # Create intention action (quick fix)
    print("\n4. Intention Actions:")
    await jetbrains.create_intention_action(
        file_path=test_file,
        range={
            'start': {'line': 12, 'character': 0},
            'end': {'line': 12, 'character': 20}
        },
        text="Add type hint",
        action_id="add_type_hint"
    )
    print("   ✓ Intention: Add type hint")
    
    # Create inspection
    print("\n5. Code Inspections:")
    await jetbrains.create_inspection(
        file_path=test_file,
        range={
            'start': {'line': 15, 'character': 0},
            'end': {'line': 15, 'character': 30}
        },
        message="Unused variable 'temp'",
        severity="WARNING"
    )
    print("   ✓ Inspection: Unused variable warning")
    
    # Show balloon notification
    print("\n6. Balloon Notification:")
    await jetbrains.show_balloon(
        message="CodeGenie analysis complete",
        message_type="info"
    )
    print("   ✓ Balloon notification shown")
    
    # Run refactoring
    print("\n7. Refactoring:")
    await jetbrains.run_refactoring(
        refactoring_type="rename",
        file_path=test_file,
        params={
            'oldName': 'old_variable',
            'newName': 'new_variable',
            'line': 20
        }
    )
    print("   ✓ Refactoring: Rename variable")
    
    # Create gutter icon
    print("\n8. Gutter Icons:")
    await jetbrains.create_gutter_icon(
        file_path=test_file,
        line=25,
        icon="run",
        tooltip="Run this test"
    )
    print("   ✓ Gutter icon: Run test")
    
    # Show tool window
    print("\n9. Tool Window:")
    await jetbrains.show_tool_window(
        window_id="CodeGenie",
        content="<html><body><h2>CodeGenie Analysis</h2></body></html>"
    )
    print("   ✓ Tool window shown")
    
    # Execute action
    print("\n10. Execute IDE Action:")
    await jetbrains.execute_action(
        action_id="ReformatCode",
        context={'file': str(test_file)}
    )
    print("   ✓ Action executed: Reformat code")
    
    print("\n✅ JetBrains integration demo complete!")


async def demo_file_sync():
    """Demonstrate file synchronization"""
    print("\n" + "=" * 60)
    print("File Synchronization Demo")
    print("=" * 60)
    
    project_root = Path.cwd()
    vscode = VSCodeBridge(project_root)
    
    # Create a test file
    test_file = project_root / "sync_test.py"
    test_file.write_text("# Original content\nprint('Hello')\n")
    
    print(f"\n1. Created test file: {test_file.name}")
    
    # First sync
    print("\n2. Initial Sync:")
    status = await vscode.sync_file(test_file)
    print(f"   In sync: {status.in_sync}")
    print(f"   Version: {status.local_version}")
    
    # Modify file
    print("\n3. Modifying file...")
    test_file.write_text("# Modified content\nprint('Hello World')\n")
    
    # Sync again
    print("\n4. Sync after modification:")
    status = await vscode.sync_file(test_file)
    print(f"   In sync: {status.in_sync}")
    print(f"   Local version: {status.local_version}")
    print(f"   Remote version: {status.remote_version}")
    if status.conflicts:
        print(f"   Conflicts: {status.conflicts}")
    
    # Get file state
    print("\n5. File State:")
    file_state = vscode.get_file_state(test_file)
    if file_state:
        print(f"   Path: {file_state.path.name}")
        print(f"   Version: {file_state.version}")
        print(f"   Checksum: {file_state.checksum[:8]}...")
        print(f"   Is dirty: {file_state.is_dirty}")
    
    # Mark as dirty
    vscode.mark_file_dirty(test_file)
    print("\n6. Marked file as dirty")
    file_state = vscode.get_file_state(test_file)
    if file_state:
        print(f"   Is dirty: {file_state.is_dirty}")
    
    # Cleanup
    test_file.unlink()
    print("\n7. Cleaned up test file")
    
    print("\n✅ File synchronization demo complete!")


async def demo_code_analysis():
    """Demonstrate code analysis and suggestions"""
    print("\n" + "=" * 60)
    print("Code Analysis and Suggestions Demo")
    print("=" * 60)
    
    project_root = Path.cwd()
    vscode = VSCodeBridge(project_root)
    
    # Sample Python code with issues
    test_code = """
def test_example():
    # This is a test function
    result = calculate_sum(1, 2)
    assert result == 3

def test_another():
    # Another test
    data = process_data([1, 2, 3])
    assert len(data) == 3
"""
    
    test_file = project_root / "test_analysis.py"
    
    print("\n1. Analyzing code...")
    await vscode.analyze_and_suggest(
        file_path=test_file,
        content=test_code,
        language="python"
    )
    
    # Get suggestions from feature manager
    feature_manager = vscode.get_feature_manager()
    
    print("\n2. Code Lenses:")
    lenses = feature_manager.lens_provider.get_lenses_for_file(test_file)
    for lens in lenses:
        print(f"   Line {lens.range.start_line}: {lens.title}")
    
    print("\n3. Quick Actions:")
    actions = feature_manager.action_provider.get_actions_for_range(
        file_path=test_file,
        start_line=0,
        start_column=0,
        end_line=100,
        end_column=0
    )
    for action in actions:
        print(f"   {action.title} ({action.action_type.value})")
    
    print("\n✅ Code analysis demo complete!")


async def main():
    """Run all demos"""
    print("\n" + "=" * 60)
    print("IDE Integration Features Demo")
    print("=" * 60)
    print("\nThis demo showcases:")
    print("  • VS Code extension interface")
    print("  • JetBrains plugin interface")
    print("  • File synchronization mechanism")
    print("  • Inline diff preview")
    print("  • Quick actions")
    print("  • Code lens integration")
    
    try:
        await demo_vscode_integration()
        await demo_jetbrains_integration()
        await demo_file_sync()
        await demo_code_analysis()
        
        print("\n" + "=" * 60)
        print("All IDE Integration Demos Complete!")
        print("=" * 60)
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    asyncio.run(main())
